DIM_DEVICE_TABLE_NAME = "dim_device"

DEVICE_LAST_POSITION_TABLE_NAME = "device_last_position"

DEVICE_ROUTE_POINTS_TABLE_NAME = "device_route_points"

DEVICE_DAILY_SUMMARY_TABLE_NAME = "device_daily_summary"

DATA_QUALITY_SUMMARY_TABLE_NAME = "data_quality_summary"


GOLD_EVENT_PARTITION_COLUMN = "event_date"

GOLD_QUALITY_PARTITION_COLUMN = "metric_date"


GOLD_DEVICE_KEY = "device_serial"


GOLD_PARTITIONED_TABLES = {
    DEVICE_ROUTE_POINTS_TABLE_NAME: (GOLD_EVENT_PARTITION_COLUMN),
    DEVICE_DAILY_SUMMARY_TABLE_NAME: (GOLD_EVENT_PARTITION_COLUMN),
    DATA_QUALITY_SUMMARY_TABLE_NAME: (GOLD_QUALITY_PARTITION_COLUMN),
}


GOLD_ENTITY_TABLES = (
    DIM_DEVICE_TABLE_NAME,
    DEVICE_LAST_POSITION_TABLE_NAME,
)
